version: "3.8"

services:
  postgres:
    image: postgres:latest
    container_name: todo-list-postgresql
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: todo-list-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  todo-list-api:
    image: todo-list-api:latest
    container_name: todo-list-api
    build: ./
    depends_on:
      - postgres
      - redis
    environment:
      NODE_ENV: ${NODE_ENV}
      DATABASE_URL: ${DATABASE_URL}
      REDIS_URL: ${REDIS_URL}
      JWT_SECRET: ${JWT_SECRET}
    ports:
      - "5000:5000"
    restart: always

volumes:
  postgres_data:
  redis-data: